repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=120]
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  - repo: local
    hooks:
      - id: smart-lint
        name: Smart Lint (flake8 + mypy with false positive handling)
        entry: python scripts/smart_lint.py
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/, -f, json, -o, bandit-report.json]
        files: ^src/

  - repo: local
    hooks:
      - id: pytest-unit
        name: Run unit tests
        entry: poetry run pytest tests/unit/ -v
        language: system
        pass_filenames: false
        always_run: false
        files: ^(src/|tests/unit/).*\.py$

      - id: complexity-check
        name: Check code complexity
        entry: poetry run radon cc src/ --min=B
        language: system
        pass_filenames: false
        always_run: false
        files: ^src/.*\.py$

default_language_version:
  python: python3.12

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
